Merge master into master-benchmark-feature (#1502)
* prepare release v2.222.0

* update development version to v2.222.1.dev0

* fix: estimator.deploy not respecting instance type (#4724)

* fix: estimator.deploy not respecting instance type

* chore: add inline comment about using user supplied instance type

* First changes (#4723)

Co-authored-by: Bryannah Hernandez <brymh@amazon.com>

* prepare release v2.222.1

* update development version to v2.222.2.dev0

* change: update image_uri_configs  06-12-2024 07:17:03 PST

* fix: Fix ci unit-tests (#4728)

* Implement custom telemetry logging in SDK (#4721)

* Fix Sniping bug fix (#4730)

* Python SDK bucket sniping fix bug

* Python SDK bucket sniping fix bug

* Minor fixes to default bucket function and fixing unit tests

* fix  - Fixes from Pylint failures

* fix  - Fixes from Flake8 failures

* fix  - More Flake8 fixes

* fix  - Remove Whitespace from blankline

* fix  - Fix black recommendations

* fix  - Adjust tabbing

---------

Co-authored-by: Jiao Liu <liujiaor@amazon.com>
Co-authored-by: liujiaor <128006184+liujiaorr@users.noreply.github.com>

* feature: add 'ModelCard' property to Register step (#4726)

* feature: add 'ModelCard' property to RegisterModel step

* Updated ModelCard content type

* fix: ModelCard Object integ Test fix

---------

Co-authored-by: Gokul A <166456257+nargokul@users.noreply.github.com>

* prepare release v2.223.0

* update development version to v2.223.1.dev0

* Fix Dependabot Issues - MLFlow Version (#4731)

* fix  - Address Dependapot issues

* fix  -Update MLFLOW Version

* Fix: AttributeError: 'NoneType' object has no attribute 'len' error in session.py (#4735)

* fix  - Address Dependapot issues

* fix  -Update MLFLOW Version

* fix  - Update fetching Length for NoneType Error

* change: Enable telemetry logging for Remote function (#4729)

* change: Enhance telemetry logging module and feature coverage

* Fix default session issue

* fix unit-tests

* chore: use ml.g5.2xlarge for integ test (#4741)

* feat: JumpStartModel attach (#4680)

* feat: JumpStartModel attach

* fix: unit tests

* chore: change order of kwargs to pass unit tests

* chore: update docstrings, add tests

* fix: docstring

* fix: integ tests

* chore: address PR comments

---------

Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* Upgrading to PT 2.3 for release (#4732)

* upgrading to PT 2.3 for release

* reverting mistake in modifying dataparallel

---------

Co-authored-by: Andrew Tian <tinandr@amazon.com>
Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* feat(sagemaker-mlflow): New features for SageMaker MLflow (#4744)

* feat: add support for mlflow inputs (#1441)

* feat: add support for mlflow inputs

* fix: typo

* fix: doc

* fix: S3 regex

* fix: refactor

* fix: refactor typo

* fix: pylint

* fix: pylint

* fix: black and pylint

---------

Co-authored-by: Jacky Lee <drjacky@amazon.com>

* fix: lineage tracking bug (#1447)

* fix: lineage bug

* fix: lineage

* fix: add validation for tracking ARN input with MLflow input type

* fix: bug

* fix: unit tests

* fix: mock

* fix: args

---------

Co-authored-by: Jacky Lee <drjacky@amazon.com>

* [Fix] regex for RunId to handle empty artifact path and change mlflow plugin name (#1455)

* [Fix] run id regex pattern such that empty artifact path is handled

* Change mlflow plugin name as per legal team requirement

* Update describe_mlflow_tracking_server call to align with api changes (#1466)

* feat: (sagemaker-mlflow) Adding Presigned Url function to SDK (#1462) (#1477)

* mlflow presigned url changes

* addressing design feedback

* test changes

* change: mlflow plugin name (#1489)

Co-authored-by: Jacky Lee <drjacky@amazon.com>

---------

Co-authored-by: Jacky Lee <dr.jackylee@gmail.com>
Co-authored-by: Jacky Lee <drjacky@amazon.com>
Co-authored-by: jiapinw <95885824+jiapinw@users.noreply.github.com>
Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* prepare release v2.224.0

* update development version to v2.224.1.dev0

* fix: Model server override logic (#4733)

* fix: Model server override logic

* Fix formatting

---------

Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* chore(deps): bump apache-airflow from 2.9.1 to 2.9.2 in /requirements/extras (#4740)

Bumps [apache-airflow](https://github.com/apache/airflow) from 2.9.1 to 2.9.2.
- [Release notes](https://github.com/apache/airflow/releases)
- [Changelog](https://github.com/apache/airflow/blob/main/RELEASE_NOTES.rst)
- [Commits](https://github.com/apache/airflow/compare/2.9.1...2.9.2)

---
updated-dependencies:
- dependency-name: apache-airflow
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* fix: Update tox.ini (#4747)

* change: Update README.rst to show conda-forge version of SageMaker SDK (#4749)

* JumpStart CuratedHub Launch (#4748)

* Implement CuratedHub APIs (#1449)

* Implement CuratedHub Admin APIs

* making some parameters optional in create_hub_content_reference as per the API design

* add describe_hub and list_hubs APIs

* implement delete_hub API

* Implement list_hub_contents API

* create CuratedHub class and supported utils

* implement list_models and address comments

* Add unit tests

* add describe_model function

* cache retrieval for describeHubContent changes

* fix curated hub class unit tests

* add utils needed for curatedHub

* Cache retrieval

* implement get_hub_model_reference()

* cleanup HUB type datatype

* cleanup constants

* rename list_public_models to list_jumpstart_service_hub_models

* implement describe_model_reference

* Rename CuratedHub to Hub

* address nit

* address nits and fix failing tests

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>

* feat: implement list_jumpstart_service_hub_models function to fetch JumpStart public hub models (#1456)

* Implement CuratedHub Admin APIs

* making some parameters optional in create_hub_content_reference as per the API design

* add describe_hub and list_hubs APIs

* implement delete_hub API

* Implement list_hub_contents API

* create CuratedHub class and supported utils

* implement list_models and address comments

* Add unit tests

* add describe_model function

* cache retrieval for describeHubContent changes

* fix curated hub class unit tests

* add utils needed for curatedHub

* Cache retrieval

* implement get_hub_model_reference()

* cleanup HUB type datatype

* cleanup constants

* rename list_public_models to list_jumpstart_service_hub_models

* implement describe_model_reference

* Rename CuratedHub to Hub

* address nit

* address nits and fix failing tests

* implement list_jumpstart_service_hub_models function

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>

* Feat/Curated Hub hub_arn and hub_content_type support (#1453)

* get_model_spec() changes to support hub_arn and hub_content_type

* implement get_hub_model_reference()

* support hub_arn and hub_content_type for specs retrieval

* add support for hub_arn and hub_content_type for serializers, deserializers, estimators, models, predictors and various spec retrieval functionalities

* address nits and test failures

* remove hub_content_type support

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>

* feat: implement curated hub parser and bug bash fixes (#1457)

* implement HubContentDocument parser

* modify the parser to remove aliases for hubcontent documents

* bug fix

* update boto3

* Bug Fix in the parser

* Improve Hub Class and related functionalities

* Bug Fix and parser updates

* add missing hub_arn support

* Add model reference deployment support and other minor bug fixes

* fix: retrieve correct image_uri (parser update)

* fix: retrieve correct model URI and model data path from HubContentDocument (parser update)

* Add model reference deployment support

* Model accessor and cache retrival bug fixes

* fix: curated hub model training workflow

* fix: pass sagemaker sessions object to retrieve model specs from describe_hub_content call

* fix: fix payload retrieval for curated hub models

* modify constants, enums

* fix: update parser

* Address nits in the parser

* Add unit tests for parser

* implement pagination for list_models utility

* feat: support wildcard chars for model versions

* Address nits and comments

* Add Hub Content Arn Tag to training and hosting

* Add Hub Content Arn Tag to training and hosting

* fix: HubContentDocument schema version

* fix broken unit tests

* fix prepare_container_def unit tests to include ModelReferenceArn

* fix unit tests for test_session.py

* revert boto version changes

* Fix unit tests

* support wildcard model versions for training workflow

* Add test cases for get_model_versions

* Add/fix unit tests

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>

* address unit tests failures in codebuild

* change list_jumpstart_service_hub_models to list_sagemaker_public_hub_models()

* fix: Changing list input output shapes

* fix: gated model training bug

* run black -l 100

* flake 8

* address formatting issues

* black -l

* DocStyle issues

* address flake8, pylint

* blake -l

* pass model type down

* disabling pylint for release

* disable pylint

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>
Co-authored-by: chrstfu <chrstfu@amazon.com>
Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>

* prepare release v2.224.1

* update development version to v2.224.2.dev0

* fix: list_models() for python3.8 (#4756)

* fix: list_models() for python3.8

* fix linting

---------

Co-authored-by: Malav Shastri <malavhs@amazon.com>

* Update DJLModel class for latest container releases (#4754)

* simplify and refactor djl model for latest container releases

* update model builder for new DJLModel implementation

* fix formatting/linting suggestions

* update DJLModel documentation on docs site

* address reviewer feedback

* Feature: Update model card on model package request (#4739)

* Feature: Update model card on model package request

* Feature: Update model card on model package request

* fix: update_model_card input types

* Feature: register proprietary models from jumpstart (#4753)

* Feature: register proprietary models from jumpstart

Feature: register proprietary models from jumpstart

* fix: register jumpstart models on model registry

* fixed get_model_id_version_from_endpoint naming issue

* fixed issues with model builder

* cleanup types.py file

* fixed jumpstart unit tests

* fixed issue in model_builder

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: ci <ci>
Co-authored-by: evakravi <69981223+evakravi@users.noreply.github.com>
Co-authored-by: bryannahm1 <110491182+bryannahm1@users.noreply.github.com>
Co-authored-by: Bryannah Hernandez <brymh@amazon.com>
Co-authored-by: sagemaker-bot <sagemaker-bot@amazon.com>
Co-authored-by: Kalyani Nikure <110067132+knikure@users.noreply.github.com>
Co-authored-by: Gokul A <166456257+nargokul@users.noreply.github.com>
Co-authored-by: Jiao Liu <liujiaor@amazon.com>
Co-authored-by: liujiaor <128006184+liujiaorr@users.noreply.github.com>
Co-authored-by: selvask-aws <selvask@amazon.com>
Co-authored-by: Erick Benitez-Ramos <141277478+benieric@users.noreply.github.com>
Co-authored-by: adtian2 <55163384+adtian2@users.noreply.github.com>
Co-authored-by: Andrew Tian <tinandr@amazon.com>
Co-authored-by: ananth102 <abashyam@amazon.com>
Co-authored-by: Jacky Lee <dr.jackylee@gmail.com>
Co-authored-by: Jacky Lee <drjacky@amazon.com>
Co-authored-by: jiapinw <95885824+jiapinw@users.noreply.github.com>
Co-authored-by: Samrudhi Sharma <154457034+samruds@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Malav Shastri <57682969+malav-shastri@users.noreply.github.com>
Co-authored-by: Malav Shastri <malavhs@amazon.com>
Co-authored-by: chrstfu <chrstfu@amazon.com>
Co-authored-by: Siddharth Venkatesan <siddvenk@umich.edu>