Revert "change: Rename data file test_hvd_basic.py to hvd_basic.py"
This reverts commit 516df2811d0b238315d0ed63fb7a16db0aca51b3.

Looks like this data file is not copied if name does not start with
test. See build failure
https://tiny.amazon.com/1abn7rx6e/devbs3amaz11a3buillog

FailureReason:
FileNotFoundError: [Errno 2] No such file or directory:
'/codebuild/output/src897959602/src/github.com/aws/sagemaker-python-sdk/tests/integ/../data/horovod/hvd_basic.py'